#!/bin/bash
outputfile="$1"
outputdir="build-x86_64-linux"

# Create output directory if it doesn't exist
mkdir -p "$outputdir"

exec /usr/bin/ghc --make xmonad.hs -i -ilib -fforce-recomp -main-is main -v0 -outputdir "$outputdir" -o "$outputfile"
